version: '3'

services:
  mongo:
    image: mongo:latest
  api:
    build:
      context: ../backend
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo:27017/surveys
    depends_on:
      - mongo
