version: "3"

services:
  mongo:
    image: mongo:latest
  api:
    build:
      context: ./backend
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo:27017/surveys
    ports:
      - 5000:5000
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
    depends_on:
      - api
    ports:
      - 3000:3000
